development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:56882b2dc4767671c0e9a09d12d888a7@crestfish.redistogo.com:10929/
  # channel_prefix: chat_app_api_production
